spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashion_db?userSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: pjw20011
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pjw200116@gmail.com      # 👉 본인 Gmail 주소
    password: uqtf dvlq zrbv zjgv         # 👉 앱 비밀번호 (2단계 인증 필수)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  spring:
    security:
      user:
        name: user
        password: 1234


  tymeleaf:
    cahe: false # HTML 변경시 실시간 반영 (개발 편의)

server:
  port: 8080
